package Test_Suite;// Generated by Selenium IDE

import org.junit.Test;

//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class AgregarCategoriaTest {

    Servicios ts = new Servicios();

//    @FindBy(xpath = "//button[contains(@class, 'css-5zrdtn')]")
//    public WebElement buttonGuardar;
//
//    @FindBy(xpath = "//button[contains(@class, 'css-lon3mv')]")
//    public WebElement buttonAgregar;
//
//    @FindBy(xpath = "//*[@id='#/properties/detalle-input']")
//
//    public WebElement inputPropertiesDetalle;
//
//    @FindBy(xpath = "//button[contains(@class, 'css-16hxacb')]")
//    public WebElement buttonCerrar;



    @Test
    public void agregarcategoria() {
        WebDriver driver = TestSuit.driver;


        ts.funcionEsperar();
        ts.funcionEsperar();
        driver.get("https://d-box-test.materiasistemas.com.ar/categorias/admin");

        ts.funcionEsperar();
        ts.funcionEsperar();

        driver.findElement(By.xpath("//button[contains(@class, 'css-lon3mv')]")).click();

        driver.findElement(By.xpath("//*[@id='#/properties/detalle-input']")).sendKeys("testSelenium");
        ts.funcionEsperar();
//        driver.findElement(By.xpath("//button[contains(@class, 'css-16hxacb')]")).click();
        
        driver.findElement(By.xpath("//button[contains(@class, 'css-5zrdtn')]")).click();

    }
}
