package Test_Suite;// Generated by Selenium IDE


import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

//import java.net.MalformedURLException;
import java.util.concurrent.TimeUnit;

@RunWith(Suite.class)
@Suite.SuiteClasses({
        LoginPage.class,
        /*AgregarCategoriaTest.class,*/
        AgregarUsuarioTest.class,
        Logout.class
        })

public class TestSuit {
    public static WebDriver driver;

    @BeforeClass
    public static void setUpClass() /*throws MalformedURLException*/ {
        System.setProperty("webdriver.chrome.driver", "C:/Users/Martin/Documents/AquaProjects/chromedriver-win32-/chromedriver.exe");
        driver = new ChromeDriver();
        driver.manage().window().setPosition(new Point(2000,0));
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);



    }

    @AfterClass
    public static void setDownClass() {

        driver.quit();
    }




}
