package PruebasAuxiliares;// Generated by Selenium IDE


import Test_Suite.AgregarCategoriaTest;
import Test_Suite.LoginPage;
import Test_Suite.Logout;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.concurrent.TimeUnit;

@RunWith(Suite.class)
@Suite.SuiteClasses({
        LoginPage.class,
        AgregarCategoriaTest.class,
        Logout.class
        })

public class Base_TestSuit {
    public static WebDriver driver;

    @BeforeClass
    public static void setUpClass(){
        System.setProperty("webdriver.chrome.driver", "C:/Users/Martin/Documents/AquaProjects/chromedriver-win32-/chromedriver.exe");
        driver = new ChromeDriver();
        driver.manage().window().setPosition(new Point(2000,0));
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

        String url = "https://d-box-test.materiasistemas.com.ar";
        driver.get(url);

    }

    @AfterClass
    public static void setDownClass() {

        driver.quit();
    }




}
